# Generated by Django 4.2.11 on 2024-07-17 18:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myquiz',
            name='duration_time',
            field=models.PositiveIntegerField(default=1, help_text='minutes', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duration time'),
        ),
    ]
