# Generated by Django 4.2.11 on 2025-05-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_myquiz_quiz_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myquiz',
            name='quiz_type',
            field=models.CharField(choices=[(1, 'Pre-course assessment'), (2, 'Midterm Exam'), (3, 'Final Exam'), (4, 'Lesson')], max_length=1),
        ),
    ]
