# Generated by Django 4.2.11 on 2025-06-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_myquiz_quiz_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='mark',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
