# Generated by Django 4.2.11 on 2025-06-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_question_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userattempt',
            name='score',
            field=models.FloatField(verbose_name='score'),
        ),
    ]
