# Generated by Django 4.2.11 on 2024-08-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_result_is_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='myquiz',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
