# Generated by Django 4.2.11 on 2025-06-16 09:01

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_answer_is_correct_alter_answer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='name',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
