# Generated by Django 4.2.11 on 2025-10-24 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_filelesson_module'),
        ('quiz', '0009_alter_question_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myquiz',
            name='lesson',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.lesson', verbose_name='lesson'),
        ),
    ]
