# Generated by Django 4.2.11 on 2024-06-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='/home/hacktivist/projects/onlineedu/static/assets/images/teacher/teacher__1.png', upload_to='media/users/', verbose_name='Image'),
        ),
    ]
