# Generated by Django 4.2.11 on 2025-06-12 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filelesson',
            name='module',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='file_lessons_by_module', to='main.module', verbose_name='module'),
            preserve_default=False,
        ),
    ]
