# Generated by Django 4.2.11 on 2024-06-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default='', max_length=150, unique=True, verbose_name='slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(default='', max_length=150, unique=True, verbose_name='slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='slug',
            field=models.SlugField(default='', max_length=150, unique=True, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
