# Generated by Django 4.2.11 on 2025-10-24 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_filelesson_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filelesson',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_lessons_by_module', to='main.module', verbose_name='module'),
        ),
    ]
