# Generated by Django 4.2.11 on 2024-08-22 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_userlessonprogress_created_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userlessonprogress',
            unique_together={('user', 'lesson', 'course')},
        ),
        migrations.RemoveField(
            model_name='userlessonprogress',
            name='course',
        ),
        migrations.AddField(
            model_name='userlessonprogress',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.course', verbose_name='course'),
            preserve_default=False,
        ),
    ]
