# Generated by Django 4.2.11 on 2024-08-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_questionanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='type',
            field=models.CharField(choices=[('question', 'Question'), ('answer', 'Answer')], default='question', max_length=9),
            preserve_default=False,
        ),
    ]
