# Generated by Django 4.2.11 on 2024-08-27 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_questionanswer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.lesson'),
        ),
    ]
